### ISSUE TITLE
Bug : ungrouped hosts should go to the default group "ungrouped"

### ISSUE THREAD

**Issue by Keyhaku** [AAbouZaid/netbox-as-ansible-inventory#19]
Hi,

It seems you created a group called "no_group" to group hosts that are in no group, but there is already a default ansible group for that : `ungrouped`

You can see more here : https://docs.ansible.com/ansible/latest/intro_inventory.html#default-groups

I think it's better to use this expected [default] group than the special one you created.

I'll submit a small PR soon.

**Comment by aabouzaid** [comment]
Thanks @Keyhaku
Waiting for your PR.
